//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.11
//
// <auto-generated>
//
// Generated from file `calculator.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Demo;

public class EmptySequenceError extends com.zeroc.Ice.UserException
{
    public EmptySequenceError()
    {
        this.reason = "Sequence can't be empty";
    }

    public EmptySequenceError(Throwable cause)
    {
        super(cause);
        this.reason = "Sequence can't be empty";
    }

    public EmptySequenceError(String reason)
    {
        this.reason = reason;
    }

    public EmptySequenceError(String reason, Throwable cause)
    {
        super(cause);
        this.reason = reason;
    }

    public String ice_id()
    {
        return "::Demo::EmptySequenceError";
    }

    public String reason;

    /** @hidden */
    @Override
    protected void _writeImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice("::Demo::EmptySequenceError", -1, true);
        ostr_.writeString(reason);
        ostr_.endSlice();
    }

    /** @hidden */
    @Override
    protected void _readImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        reason = istr_.readString();
        istr_.endSlice();
    }

    /** @hidden */
    public static final long serialVersionUID = 1399525881L;
}
